version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "15:43"
      timezone: America/Phoenix
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "16:03"
      timezone: America/Phoenix
    open-pull-requests-limit: 5

