// Generated by scripts/build-study-manifests.mjs.
export const STUDY_BEHAVIOR_HASHES: Readonly<Record<string,string>> = {
  "trendvol-ml-ridge-shadow-v2": "90e16220230fef0b86b68e13dd1931c3a2077487ae435fc03627d18949ee8901",
  "wider-breakout-v1": "0f938dcfc8a8a3b2ab79ea9aad5eb926e1b6bd03e99d03ad857bd3d8744d460d",
  "wider-range-rotation-v1": "c46686ec6fb20467d61a6bea5b5e3b92b2bdfafcebcd4a4a95aafd4de3bfe16b",
  "paper-market-selector-v1": "b9069d666542e7a8556861315b6dcbd85d6e4ca1dcf19aea2352d27fc4d6d47a",
  "trendvol-hourly-execution-v1": "a86acb4608fa544155137e1814d19201628254de6c93772fb29bc5fc845b3178",
  "trendvol-execution-remediation-v1": "9ad62cacd7a6a1ac9a2e7deea2a34d56eefa32a1bc4fc281eaf8cb07e37a7504"
};
