// Generated by scripts/build-study-manifests.mjs.
export const STUDY_BEHAVIOR_HASHES: Readonly<Record<string,string>> = {
  "trendvol-ml-ridge-shadow-v2": "827b90cc56563422d905b3850c12ecd3ec4aa69334ebd23f6b33200d40e3f488",
  "wider-breakout-v1": "a0242ad3a2c9fa349cb02d66bbbe1dbfa1b809f3aa01c084853594ea53d0d956",
  "wider-range-rotation-v1": "0974dddaf750ff6443674960d22b4dcec9752e3426cf0ac5f76ecfda56bd6b9d",
  "paper-market-selector-v1": "70db6046c42947c7808fe9989f087aa4ff477bc66958e2d05f70654a61503efd",
  "trendvol-hourly-execution-v1": "1c039e7ed4e090fccc0d9c2eb0622a3d968ab0b251ad4c590c4813d9a46bbd05",
  "trendvol-execution-remediation-v1": "fe0d749fb44f60df738dab066044135b2e05f7d4cbdd037d8aa750d40f8c081e"
};
