// Generated by scripts/build-study-manifests.mjs.
export const STUDY_BEHAVIOR_HASHES: Readonly<Record<string,string>> = {
  "trendvol-ml-ridge-shadow-v2": "b1bc098f2cf51cf3259e372e023ae775849aba0c23dd2aac055a54676f37e7f3",
  "wider-breakout-v1": "2f5ef2b297510177f68420f5d645e13aca7b034d06f23a9d62961007506d8a89",
  "wider-range-rotation-v1": "271c3ca019bea5fd765da3c5c45f7b43e9e5a532bffaba13e45108c2775223f6",
  "paper-market-selector-v1": "c00b79321d76b22dcee8dd653faab4989e1487b25b4d1c79130f3d936511c445",
  "trendvol-hourly-execution-v1": "c8b4eab46cd17c73406bc01a130875dbfa5c7538b1148bdaa3aa7870291a58fd",
  "trendvol-execution-remediation-v1": "8a727e186e2e62749b5b777d605c4e49db21933b94b89d4fba60381468962256"
};
