import * as z from 'zod';

import { epochMillisecondsSchema } from '../messages.js';

const command = z.strictObject({ commandId: z.string().uuid() }).readonly();
const activity = z.strictObject({
  id: z.string().length(64),
  atMs: epochMillisecondsSchema,
  kind: z.enum(['decision', 'intent', 'submission', 'order', 'fill', 'fee', 'retry', 'no_trade', 'complete', 'paused', 'resumed', 'stopped', 'missed', 'check', 'skip', 'policy', 'ml']),
  title: z.string().max(120),
  detail: z.string().max(300),
  alpacaOrderId: z.string().max(128).nullable(),
}).readonly();
const status = z.strictObject({
  experimentId: z.string().length(64).nullable(),
  state: z.enum(['none', 'active', 'paused', 'stopped']),
  startedAtMs: epochMillisecondsSchema.nullable(),
  coquiOpeningUsd: z.string().nullable(),
  alpacaOpeningUsd: z.string().nullable(),
  coquiEquityUsd: z.string().nullable(),
  alpacaEquityUsd: z.string().nullable(),
  coquiReturnPct: z.string().nullable(),
  alpacaReturnPct: z.string().nullable(),
  lastMarkDay: z.string().nullable(),
  decisionCount: z.number().int().nonnegative(),
  runtimeState: z.enum(['none', 'awaiting', 'evaluating', 'order_pending', 'reconciled', 'intraday', 'paused', 'attention', 'stopped']),
  lastCheckAtMs: epochMillisecondsSchema.nullable(),
  lastDecisionAtMs: epochMillisecondsSchema.nullable(),
  latestDecision: z.strictObject({
    day: z.string(), exposurePct: z.string(), cashPct: z.string(), mixVolPct: z.string(),
    belowTrend: z.boolean(),
    filters: z.strictObject({ negativeMomentumAssets: z.number().int().nonnegative(),
      assetVolScaledAssets: z.number().int().nonnegative(), portfolioVolScaled: z.boolean(),
      trendCapApplied: z.boolean() }).nullable(),
    targets: z.array(z.strictObject({ symbol: z.string(), weightPct: z.string() }).readonly()).max(3).readonly(),
  }).nullable(),
  filterSummary: z.strictObject({ observedDecisions: z.number().int().nonnegative(),
    negativeMomentumDays: z.number().int().nonnegative(), assetVolScaledDays: z.number().int().nonnegative(),
    portfolioVolScaledDays: z.number().int().nonnegative(), trendCapDays: z.number().int().nonnegative() }),
  activity: z.array(activity).max(20).readonly(),
  mlSignal: z.strictObject({
    gate: z.enum(['collecting', 'unqualified', 'qualified']), reason: z.string(),
    version: z.string().nullable(), modelHash: z.string().length(64).nullable(),
    datasetHash: z.string().length(64).nullable(), predictedAtMs: epochMillisecondsSchema.nullable(),
    evidence: z.strictObject({ developmentSlots: z.number(), holdoutSlots: z.number(),
      baselineReturnPct: z.number(), mlReturnPct: z.number(), liftPct: z.number(),
      stressLiftPct: z.number(), maxDrawdownPct: z.number(), turnover: z.number(),
      tradeCount: z.number(), lift95LowPct: z.number(), lift95HighPct: z.number() }).nullable(),
    lastSlot: z.string().nullable(), lastApplied: z.boolean().nullable(), lastReason: z.string().nullable(),
    lastBaseline: z.array(z.strictObject({ symbol: z.string(), weightPct: z.string() })).max(3),
    lastProposed: z.array(z.strictObject({ symbol: z.string(), weightPct: z.string() })).max(3),
    lastCombined: z.array(z.strictObject({ symbol: z.string(), weightPct: z.string() })).max(3),
  }),
  hourlyShadow: z.strictObject({
    version: z.literal('trendvol-hourly-execution-v1'), mode: z.literal('shadow'),
    startMs: epochMillisecondsSchema.nullable(), lastSlotMs: epochMillisecondsSchema.nullable(),
    observationCount: z.number().int().nonnegative(), completeDays: z.number().int().nonnegative(),
    lastModeledOrderCount: z.number().int().nonnegative(),
    lastModeledOrders: z.array(z.strictObject({ symbol: z.string().max(16), side: z.enum(['buy', 'sell']),
      quantity: z.string(), filledQuantity: z.string(), remainingQuantity: z.string() })).max(3),
    lastBlockedReasons: z.array(z.string().max(80)).max(3),
    lastFailureReason: z.string().max(80).nullable(),
  }),
  coquiFillCount: z.number().int().nonnegative(),
  alpacaFillCount: z.number().int().nonnegative(),
  alpacaOrderCount: z.number().int().nonnegative(),
  coquiFeesUsd: z.string(),
  alpacaBookedFeesUsd: z.string().nullable(),
  alpacaModeledFrictionUsd: z.string(),
  positions: z.array(z.strictObject({ symbol: z.string(), coquiQty: z.string(), alpacaQty: z.string(),
    coquiValueUsd: z.string(), alpacaValueUsd: z.string() }).readonly()).max(3).readonly(),
  targets: z.array(z.strictObject({ symbol: z.string(), weightPct: z.string() }).readonly()).max(3).readonly(),
  recentTrades: z.array(z.strictObject({ source: z.enum(['coqui', 'alpaca_paper']),
    atMs: epochMillisecondsSchema, symbol: z.string(), quantity: z.string(),
    price: z.string(), feeUsd: z.string().nullable() }).readonly()).max(20).readonly(),
  lastReason: z.string().max(80).nullable(),
  paperOnly: z.literal(true),
}).readonly();

export const parallelPaperChannelSchemas = {
  'parallel.paper.status': { request: z.strictObject({}).readonly(), response: status },
  'parallel.paper.start': { request: z.strictObject({ commandId: z.string().uuid(),
    smokeVerified: z.literal(true) }).readonly(), response: status },
  'parallel.paper.pause': { request: command, response: status },
  'parallel.paper.resume': { request: command, response: status },
  'parallel.paper.stop': { request: command, response: status },
} as const;
